projManager/clients/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 10 18:00:15 2017

@author: jcuartas
"""

from django.conf.urls import url
from clients.views import ShowClass
from clients.views import LoginClass
from clients.views import logout
from clients.views import DashboardClass
from clients.views import CreateClass
from clients.views import EditClass
from clients.views import edit_password
from clients.views import edit_client

app_name = 'client'

urlpatterns = [
#    url(r'^show/(?P<pk>\d+)/$', views.ShowView.as_view(), name = 'show'),    
    url(r'^show/(?P<username_url>\w+)/$', ShowClass.as_view(), name = 'show'),
    url(r'^login/$', LoginClass.as_view(), name = 'login'),
    url(r'^logout/$', logout, name = 'logout'),
    url(r'^dashboard/$', DashboardClass.as_view(), name = 'dashboard'),
    url(r'^create/$', CreateClass.as_view(), name = 'create'),
    url(r'^edit/$', EditClass.as_view(), name = 'edit'),
    url(r'^edit_password/$', edit_password, name = 'edit_password'),
    url(r'^edit_client/$', edit_client, name = 'edit_client'),          
]

projManager/projManager/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

from .views import home
from .views import error_404

urlpatterns = [
    url(r'^$', home, name = 'home'),
    url(r'^admin/', admin.site.urls),
    url(r'^clients/', include('clients.urls')),
]

handler404 = error_404

projManager/templates/bases/base_admin.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title> {% block title %} {% endblock %} </title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/mateialize.min.js"></script>
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    
    {% block scripts %} {% endblock %}
</head>
    <header>
        <div class="nav-wrapper #9e9e9e grey">
            <a href="{% url 'home' %}" class="brand-logo">Project Manager</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down lighten-2">
                <li><a href="{% url 'client:login' %}">Login</a></li>
                <li><a href="{% url 'client:create' %}">Registro</a></li>
            </ul>
            <ul class="side-nav" id="mobile-demo">
                <li><a href="{% url 'client:login' %}">Login</a></li>
                <li><a href="{% url 'client:create' %}">Registro</a></li>
            </ul>
        </div>
    </header>
    
    {% if messages %}
        <ul>
        {% for message in messages %}
            <li {% if message.tags %} class= "{{message.tags}}_message"{% endif %}>{{ message }}</li>
            
        {% endfor %}
        </ul>    
    {% endif %}

    {%block content %} {%endblock%}
    
    {%block footer %} {%endblock%}
    
</html>