projManager/clients/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 10 18:00:15 2017

@author: jcuartas
"""

from django.conf.urls import url
from clients.views import ShowClass
from clients.views import LoginClass
from clients.views import logout
from clients.views import DashboardClass
from clients.views import CreateClass
from clients.views import EditClass
from clients.views import edit_password
from clients.views import edit_client

app_name = 'client'

urlpatterns = [
#    url(r'^show/(?P<pk>\d+)/$', views.ShowView.as_view(), name = 'show'),    
    url(r'^show/(?P<username_url>\w+)/$', ShowClass.as_view(), name = 'show'),
    url(r'^login/$', LoginClass.as_view(), name = 'login'),
    url(r'^logout/$', logout, name = 'logout'),
    url(r'^dashboard/$', DashboardClass.as_view(), name = 'dashboard'),
    url(r'^create/$', CreateClass.as_view(), name = 'create'),
    url(r'^edit/$', EditClass.as_view(), name = 'edit'),
    url(r'^edit_password/$', edit_password, name = 'edit_password'),
    url(r'^edit_client/$', edit_client, name = 'edit_client'),          
]

projManager/projManager/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

from .views import home
from .views import error_404

urlpatterns = [
    url(r'^$', home, name = 'home'),
    url(r'^admin/', admin.site.urls),
    url(r'^clients/', include('clients.urls')),
]

handler404 = error_404

projManager/clients/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Client(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE )
    job = models.CharField(max_length=100, default = "")
    bio = models.TextField(max_length=200, default = "")

projManager/clients/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 10 19:26:21 2017

@author: jcuartas
"""

from django import forms
from django.contrib.auth.models import User
from .models import Client

"""
Constants
"""

ERROR_MESSAGE_USER = {'required': 'El username es requerido', 'unique':'El usuario ya se encuentra registrado', 'invalid':'El username es incorrecto'}
ERROR_MESSAGE_PASSWORD = {'required': 'El password es requerido'}
ERROR_MESSAGE_EMAIL = {'required': 'El email es requerido', 'invalid':'Ingrese un correo valido'}


"""
Functions
"""
def must_be_gt(value_password):
    if len(value_password) < 5:
        raise forms.ValidationError('El password debe contener por lo menos 5 caracteres, desde una func')

"""
Class
"""

class LoginUserForm(forms.Form):
    username = forms.CharField( max_length = 20)
    password = forms.CharField( max_length = 20, widget = forms.PasswordInput() )
    
    def __init__(self, *args, **kwargs):
        super(LoginUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update( {'id': 'username_login', 'class':'input_login'} )
        self.fields['password'].widget.attrs.update( {'id': 'password_login', 'class':'input_login'} )
    
class CreateUserForm(forms.ModelForm):
    username = forms.CharField( max_length = 20, error_messages = ERROR_MESSAGE_USER)
    password = forms.CharField( max_length = 20, widget = forms.PasswordInput(), error_messages = ERROR_MESSAGE_PASSWORD)
    email = forms.CharField(error_messages = ERROR_MESSAGE_EMAIL)

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update( {'id': 'username_create'} )
        self.fields['password'].widget.attrs.update( {'id': 'password_create'} )
        self.fields['email'].widget.attrs.update( {'id': 'email_create'} )

    class Meta:
        model = User
        fields = ('username', 'password', 'email')
        

class EditUserForm(forms.ModelForm):
    username = forms.CharField( max_length = 20, error_messages = ERROR_MESSAGE_USER)
    email = forms.CharField(error_messages = ERROR_MESSAGE_EMAIL)
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

class EditPasswordForm(forms.Form):
    password = forms.CharField( max_length = 20, widget = forms.PasswordInput() )
    new_password = forms.CharField( max_length = 20, widget = forms.PasswordInput(), validators = [must_be_gt] )
    repeat_password = forms.CharField( max_length = 20, widget = forms.PasswordInput(), validators = [must_be_gt] )
    
    def clean(self):
        clean_data = super(EditPasswordForm, self).clean()

        if 'new_password' in clean_data.keys():
            password1 = clean_data['new_password']
        else:
            password1 = ''
        if 'repeat_password' in clean_data.keys():
            password2 = clean_data['repeat_password']
        else:
            password2 = ''
        if password1 == '' or password2 == '':
            raise forms.ValidationError('Nuevo pasword inválido')
        if password1 != password2:
            raise forms.ValidationError('Los password no son los mismos')
 
class EditClientForm(forms.ModelForm):
    class Meta:
        model = Client
#         fields = ('bio', 'job')
        exclude = ['user']

projManager/clients/views.py
from django.contrib.auth.models import User
from .models import Client

from django.shortcuts import render
from django.shortcuts import redirect

from clients.forms import LoginUserForm
from clients.forms import CreateUserForm
from clients.forms import EditUserForm
from clients.forms import EditPasswordForm
from clients.forms import EditClientForm

from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth import logout as logout_django
from django.contrib.auth import update_session_auth_hash

from django.contrib.auth.decorators import login_required

from django.views.generic import View
from django.views.generic import TemplateView
from django.views.generic import DetailView
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
# Create your views here.
"""
Class
"""

class ShowClass(DetailView): # Vista publica, cada persona puede entrar a perfiles.
    model = User
    template_name = 'client/show.html'
    slug_field = 'username' # Que campo de la base de datos
    slug_url_kwarg = 'username_url' #Que de la url
    
#def show(request):
#    return HttpResponse("Hola desde el cliente")

#def login(request):
#    nombre = 'Juan Manuel'
#    edad = 34
#    context = { 'nombre' : nombre, 'edad' : edad  }
#    return render(request, 'login.html', context)

class LoginClass(View):
    form = LoginUserForm()
    message = None
    template = 'client/login.html'
    
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('client:dashboard')
        return render(request, self.template, self.get_context())
    
    def post(self, request, *args, **kwargs):
        
        username_post = request.POST['username']
        password_post = request.POST['password']
        
        user = authenticate (username = username_post, password = password_post)
        if user is not None:
            login_django(request, user)
            return redirect('client:dashboard')
        else:
            self.message = "Username o password incorrecto"
        return render(request, self.template, self.get_context())
    
    def get_context(self):
        return {'form': self.form, 'message':self.message}
    
class DashboardClass(LoginRequiredMixin, View): #Mixin porque el usuario debe estar autenticado
    login_url = 'client:login'
    
    def get(self, request, *args, **kwargs): #Heredada de View
        return render( request, 'client/dashboard.html', {})

   
class CreateClass(CreateView):
    success_url = reverse_lazy('client:login')
    template_name = 'client/create.html'
    model = User
    form_class = CreateUserForm
    
    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.set_password ( self.object.password)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
    
class EditClass(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
    login_url = 'client:login'
    model = User
    template_name = 'client/edit.html'
    success_url = reverse_lazy('client:edit')
    form_class = EditUserForm
    success_message = "Tu usuario ha sido actualizado"
    
    def form_valid(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(EditClass, self).form_valid(request)
    
    def get_object(self, queryset = None):
        return self.request.user
 
    
"""
Functions
"""

@login_required( login_url = 'client:login' )       
def edit_password(request):
    
    form = EditPasswordForm(request.POST or None)
    context = {'form' : form}
    if request.method == 'POST':
        if form.is_valid():
            current_password = form.cleaned_data['password']
            new_password = form.cleaned_data['new_password']
            if authenticate(username = request.user.username, password = current_password):
                request.user.set_password(new_password)
                request.user.save()
                
                update_session_auth_hash(request, request.user)
                messages.success(request, 'Password actualizado.')
            else:
                messages.error(request, 'No es posible actualizar el password.')
    context = {'form' : form}
    return render(request, 'client/edit_password.html', context)

@login_required( login_url = 'client:login' )
def logout(request):
    logout_django(request)
    return redirect('client:login')

@login_required( login_url = 'client:login' )
def edit_client(request):
    form = EditClientForm( request.POST or None, instance = client_instance(request.user) )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'Datos actualizados correctamente')
    context = {'form':form}
    return render(request, 'client/edit_client.html', context)

def client_instance(user):
    try:
        return user.client
    except:
        return Client(user = user)
#def login(request):
#    if request.user.is_authenticated():
#        return redirect('client:dashboard')
#    message = None
#    if request.method == 'POST': # Nos estan enviando el formulario
#        username_post = request.POST['username']
#        password_post = request.POST['password']
#        
#        user = authenticate (username = username_post, password = password_post)
#        if user is not None:
#            login_django(request, user)
#            return redirect('client:dashboard')
#        else:
#            message = "Username o password incorrecto"
#        
#    form = LoginForm()
#    context = {
#        'form' : form,
#        'message' : message
#        
#    }
#    return render(request, 'login.html', context)

#@login_required( login_url = 'client:login' ) # Si el usuario esta autenticado entra
#def dashboard(request):
#    return render( request, 'dashboard.html', {})

#def create(request):
#    form = CreateUserForm(request.POST or None)
#    if request.method == 'POST':
#        if form.is_valid():
#            user = form.save( commit = False )
#            user.set_password( user.password )
#            user.save()
#            return redirect('client:login')
#    context = {
#        'form' : form
#    }
#    return render( request, 'create.html', context)
    

projManager/templates/client/create.html
{% extends 'bases/base_admin.html' %}

{% block title %} Project Manager {% endblock %}

{% block scripts %}
    {%load staticfiles%}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
    <form method="post" action="" class="class_container_form">
        {% csrf_token %}
        {# {{ form.as_p }} #}
        {% for field in form %}
            <div class="row">
                <div class="input-field col s12">
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}
                    
                    {{ field }}
                    
                    <label class="{% for class in field.label_classes %} {{ class }} {% endfor %}" for="{{ field.name }}"> {{ field.label }} </label>
                </div>
            </div>
        {% endfor %}
        <input class="btn #9e9e9e grey" type="submit" value="Registro">
    </form>

{% endblock %}

{% block footer %}
    <footer>
        <p>Ya cuento con una <a href="{% url 'client:login' %}">cuenta</a></p>
    </footer>
{% endblock %}

projManager/templates/client/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Dashboard</title>
</head>
<body>
    <h3>Bienvenido {{ user.username|title}}</h3>

    <a href="{% url 'client:edit' %}">Editar</a>
    <a href="{% url 'client:edit_password' %}">Editar Password</a>
    <a href="{% url 'client:show' user.username %}">Ver Perfil</a>
    <a href="{% url 'client:logout' %}">Salir</a>
</body>
</html>

projManager/templates/client/edit.html
{% extends 'client/bases/edit_base.html' %}

{%block title%} Editar Usuario {%endblock%}

{%block subtitle%} Editar Usuario {%endblock%}

{%block content %} 
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="actualizar">
    </form>
{%endblock%}

projManager/templates/client/edit_client.html
<html>
<head>
    <title>Editar Cliente</title>
</head>
<body>
    
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Actualizar">
    </form>

</body>
</html>

projManager/templates/client/edit_password.html
{% extends 'client/bases/edit_base.html' %}

{%block title%} Editar Password {%endblock%}

{%block subtitle%} Editar Password {%endblock%}

{%block content %} 
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Actualizar Password">
    </form>
{%endblock%}

projManager/templates/client/login.html
{% extends 'bases/base_admin.html' %}

{% block title %} Project Manager {% endblock %}

{% block scripts %}
    {%load staticfiles%}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
    <form method="post" action="" class="class_container_form">
        {% csrf_token %}
        {# {{ form.as_p }} #}
        {% for field in form %}
            <div class="row">
                <div class="input-field col s12">
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}
                    
                    {{ field }}
                    
                    <label class="{% for class in field.label_classes %} {{ class }} {% endfor %}" for="{{ field.name }}"> {{ field.label }} </label>
                </div>
            </div>
        {% endfor %}
        <input class="btn #9e9e9e grey" type="submit" value="ingreso">
    </form>
{% endblock %}

{% block footer %}
    <footer>
        <a href="#">Olvidé mi contraseña</a>
        <p> Crea una nueva cuenta <a href="{% url 'client:create' %}">aquí</a></p>
    </footer>
{% endblock %}

projManager/templates/client/show.html
<h3>Hola Usuario {{ user.username }}</h3>